Replace usage of eventing v1beta1 APIs with v1
google/knative-gcp pull request #2197
Opened 2021-04-15 17:07 UTC by grantr

The v1beta1 versions of Broker and Trigger have been removed from upstream. The v1 version has an identical schema, so replacing is just import juggling.

This should unblock the auto dependency update.

## Proposed Changes

- 🗑️ Remove support for Broker and Trigger v1beta1

**Release Note**

```release-note
## Action Required
The v1beta1 versions of Broker and Trigger are no longer supported. Please switch to the v1 versions of these resources (schema is identical).
```

2021-04-15 17:09 UTC, grantr commented
/approve

2021-04-15 17:09 UTC, grantr commented
Seems like we inherited the change to remove self-approval from Knative test-infra. This change is likely to be reverted in Knative, so we probably don't need to do anything to revert it ourselves.

2021-04-19 18:26 UTC, eclipselu requested changes

2021-04-19 18:26 UTC, eclipselu commented on test/lib/helpers/broker_event_transformation_test_with_source.go
>  		eventingtestresources.WithSubscriberServiceRefForTriggerV1Beta1(targetName),
This needs to be changed to V1 versions as well.

2021-04-19 18:26 UTC, eclipselu commented on test/lib/helpers/broker_event_transformation_test_with_source.go
>  		eventingtestresources.WithSubscriberServiceRefForTriggerV1Beta1(kserviceName),
This needs to be changed to [client.Core.CreateTriggerOrFail](https://github.com/knative/eventing/blob/main/test/lib/creation.go#L251), and WithSubscriberServiceRefForTriggerV1

2021-04-19 18:40 UTC, eclipselu commented on test/lib/helpers/broker_event_transformation_test_with_source.go
>  	return client.Core.CreateTriggerOrFailV1Beta1(
```suggestion
	return client.Core.CreateTriggerOrFail(
```

2021-04-19 18:40 UTC, eclipselu commented on test/lib/helpers/broker_event_transformation_test_with_source.go
>  		eventingtestresources.WithSubscriberServiceRefForTriggerV1Beta1(kserviceName),
```suggestion
		eventingtestresources.WithSubscriberServiceRefForTriggerV1(kserviceName),
```

2021-04-19 18:40 UTC, eclipselu commented on test/lib/helpers/broker_event_transformation_test_with_source.go
>  		eventingtestresources.WithSubscriberServiceRefForTriggerV1Beta1(targetName),
```suggestion
		eventingtestresources.WithSubscriberServiceRefForTriggerV1(targetName),
```

2021-04-19 18:40 UTC, eclipselu commented on test/lib/helpers/broker_event_transformation_test_with_source.go
>  	return client.Core.CreateTriggerOrFailV1Beta1(
```suggestion
	return client.Core.CreateTriggerOrFail(
```

2021-04-19 21:35 UTC, grantr commented
/retest

2021-04-23 18:19 UTC, grantr commented
/retest

2021-04-26 20:34 UTC, danyinggu commented
It seems like we need to run update-codegen.sh again.

2021-04-27 22:08 UTC, grantr commented
I'm unable to get Prow's update-codegen.sh output locally. When I run it I don't get a diff. Maybe I have an environment difference?

2021-05-05 16:55 UTC, closed without merging